name: Ansible Deployemnt

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2
    - uses: ./.github/actions

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: "playbook.yml"
        args: "-q"
